### ISSUE TITLE
Delete Assignment Command is not consistent with AB3 commands

### ISSUE THREAD

**Issue by lm-44** [AY2425S1-CS2103-F11-1/tp#178]
e.g.
Edit Student "edit_student 1 p/91234567 e/johndoe@example.com"
Delete Assignment "delete_assignment studentIndex/1 assignmentIndex/1"

Student Index needs to have a prefix before it. Ideally, both student index and assignment index should not require it, however, a justification can be made for assignment index to make sure the user knows which index refers to which before making an irreversible command

This might also file under "Feature Flaw"
![image](https://github.com/user-attachments/assets/b2e59426-dee4-496a-8c26-e75755e43096)

**Comment by avrilmohh** [comment]
I agree, I think studentIndex and assignmentIndex is too long as prefixes, rather than just removing the prefix for studentIndex entirely, maybe we can shorten both prefixes? For example studentIndex can be "si/" and assignmentIndex can be "ai"

The same could be applied to the other long prefixes too
